# Generated by Django 5.2.1 on 2025-06-05 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Questao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "texto_pergunta",
                    models.TextField(help_text="O texto completo da pergunta."),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordem da pergunta dentro do quiz, conforme o arquivo original.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questão",
                "verbose_name_plural": "Questões",
                "ordering": ["quiz_carregado", "ordem"],
            },
        ),
        migrations.CreateModel(
            name="Alternativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "texto_alternativa",
                    models.CharField(
                        help_text="O texto da alternativa.", max_length=500
                    ),
                ),
                (
                    "eh_correta",
                    models.BooleanField(
                        default=False,
                        help_text="Marque se esta é a alternativa correta.",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordem da alternativa dentro da questão, conforme o arquivo original.",
                    ),
                ),
                (
                    "questao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternativas",
                        to="quiz.questao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alternativa",
                "verbose_name_plural": "Alternativas",
                "ordering": ["questao", "ordem"],
            },
        ),
        migrations.CreateModel(
            name="QuizCarregado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo_quiz",
                    models.CharField(
                        help_text="Título do quiz, pode ser o nome do arquivo ou um título personalizado.",
                        max_length=255,
                    ),
                ),
                (
                    "data_upload",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora em que o quiz foi carregado.",
                    ),
                ),
                (
                    "usuario_que_carregou",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quizzes_carregados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Carregado",
                "verbose_name_plural": "Quizzes Carregados",
                "ordering": ["-data_upload"],
            },
        ),
        migrations.AddField(
            model_name="questao",
            name="quiz_carregado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questoes",
                to="quiz.quizcarregado",
            ),
        ),
    ]
